apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pod-security-webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pod-security-webhook.labels" . | nindent 4 }}
