---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-security-webhook
  namespace: tritonai-system

---
# The webhook needs read access to Namespace objects to fetch annotations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-security-webhook
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-security-webhook
subjects:
  - kind: ServiceAccount
    name: pod-security-webhook
    namespace: tritonai-system
roleRef:
  kind: ClusterRole
  name: pod-security-webhook
  apiGroup: rbac.authorization.k8s.io
